config/routes.rb
Rails.application.routes.draw do
  resources :archives
  resources :pasta
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
end

app/models/pastum.rb
class Pastum < ApplicationRecord
    
    has_many :archives
    has_many :subdiretorio, class_name: "Pastum", foreign_key: "id_pasta"
    belongs_to :pasta_raiz, class_name: "Pastum"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: %i[ show edit update destroy ]

  # GET /archives or /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1 or /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives or /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: "Archive was successfully created." }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1 or /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: "Archive was successfully updated." }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1 or /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: "Archive was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def archive_params
      params.require(:archive).permit(:nome, :caminho)
    end
end

app/controllers/pasta_controller.rb
class PastaController < ApplicationController
  before_action :set_pastum, only: %i[ show edit update destroy ]

  # GET /pasta or /pasta.json
  def index
    @pasta = Pastum.all
  end

  # GET /pasta/1 or /pasta/1.json
  def show
  end

  # GET /pasta/new
  def new
    @pastum = Pastum.new
  end

  # GET /pasta/1/edit
  def edit
  end

  # POST /pasta or /pasta.json
  def create
    @pastum = Pastum.new(pastum_params)

    respond_to do |format|
      if @pastum.save
        format.html { redirect_to @pastum, notice: "Pastum was successfully created." }
        format.json { render :show, status: :created, location: @pastum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pastum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pasta/1 or /pasta/1.json
  def update
    respond_to do |format|
      if @pastum.update(pastum_params)
        format.html { redirect_to @pastum, notice: "Pastum was successfully updated." }
        format.json { render :show, status: :ok, location: @pastum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pastum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pasta/1 or /pasta/1.json
  def destroy
    @pastum.destroy
    respond_to do |format|
      format.html { redirect_to pasta_url, notice: "Pastum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pastum
      @pastum = Pastum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pastum_params
      params.require(:pastum).permit(:nome, :id_pasta)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/pasta_helper.rb
module PastaHelper
end

app/views/archives/_form.html.erb
<%= form_with(model: archive, local: true) do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :caminho %>
    <%= form.text_field :caminho %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Archives</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Caminho</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.nome %></td>
        <td><%= archive.caminho %></td>
        <td><%= link_to 'Show', archive %></td>
        <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_archive_path %>

app/views/archives/new.html.erb
<h1>New Archive</h1>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @archive.nome %>
</p>

<p>
  <strong>Caminho:</strong>
  <%= @archive.caminho %>
</p>

<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pasta/_form.html.erb
<%= form_with(model: pastum, local: true) do |form| %>
  <% if pastum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pastum.errors.count, "error") %> prohibited this pastum from being saved:</h2>

      <ul>
      <% pastum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :id_pasta %>
    <%= form.text_field :id_pasta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pasta/edit.html.erb
<h1>Editing Pastum</h1>

<%= render 'form', pastum: @pastum %>

<%= link_to 'Show', @pastum %> |
<%= link_to 'Back', pasta_path %>

app/views/pasta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pasta</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id pasta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pasta.each do |pastum| %>
      <tr>
        <td><%= pastum.nome %></td>
        <td><%= pastum.id_pasta %></td>
        <td><%= link_to 'Show', pastum %></td>
        <td><%= link_to 'Edit', edit_pastum_path(pastum) %></td>
        <td><%= link_to 'Destroy', pastum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pastum', new_pastum_path %>

app/views/pasta/new.html.erb
<h1>New Pastum</h1>

<%= render 'form', pastum: @pastum %>

<%= link_to 'Back', pasta_path %>

app/views/pasta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pastum.nome %>
</p>

<p>
  <strong>Id pasta:</strong>
  <%= @pastum.id_pasta %>
</p>

<%= link_to 'Edit', edit_pastum_path(@pastum) %> |
<%= link_to 'Back', pasta_path %>